version: '3'
services:
  mysqldb:
    image: mysql:5.7
    ports:
    - "33061:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superSecret
      MYSQL_DATABASE: nest_lambda
      MYSQL_USER: nest
      MYSQL_PASSWORD: lambda

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - SERVICES=iam,lambda,apigateway,s3,sns
      - DEBUG=1
      - DATA_DIR=./tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=./tmp/localstack
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"